# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\live_streaming_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.selectModelOFFBtn = QtWidgets.QPushButton(self.frame_2)
        self.selectModelOFFBtn.setObjectName("selectModelOFFBtn")
        self.verticalLayout_2.addWidget(self.selectModelOFFBtn)
        self.offThreshLabel = QtWidgets.QLabel(self.frame_2)
        self.offThreshLabel.setObjectName("offThreshLabel")
        self.verticalLayout_2.addWidget(self.offThreshLabel)
        self.inputThreshOFF = QtWidgets.QLineEdit(self.frame_2)
        self.inputThreshOFF.setObjectName("inputThreshOFF")
        self.verticalLayout_2.addWidget(self.inputThreshOFF)
        spacerItem = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.selectModelONBtn = QtWidgets.QPushButton(self.frame_2)
        self.selectModelONBtn.setObjectName("selectModelONBtn")
        self.verticalLayout_2.addWidget(self.selectModelONBtn)
        self.onThreshLabel = QtWidgets.QLabel(self.frame_2)
        self.onThreshLabel.setObjectName("onThreshLabel")
        self.verticalLayout_2.addWidget(self.onThreshLabel)
        self.inputThreshON = QtWidgets.QLineEdit(self.frame_2)
        self.inputThreshON.setClearButtonEnabled(False)
        self.inputThreshON.setObjectName("inputThreshON")
        self.verticalLayout_2.addWidget(self.inputThreshON)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelStreams = QtWidgets.QLabel(self.frame_3)
        self.labelStreams.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStreams.setObjectName("labelStreams")
        self.verticalLayout.addWidget(self.labelStreams)
        self.updateStreamsBtn = QtWidgets.QPushButton(self.frame_3)
        self.updateStreamsBtn.setObjectName("updateStreamsBtn")
        self.verticalLayout.addWidget(self.updateStreamsBtn)
        self.streamList = QtWidgets.QListWidget(self.frame_3)
        self.streamList.setObjectName("streamList")
        self.verticalLayout.addWidget(self.streamList)
        self.StartStreamBtn = QtWidgets.QPushButton(self.frame_3)
        self.StartStreamBtn.setObjectName("StartStreamBtn")
        self.verticalLayout.addWidget(self.StartStreamBtn)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.SignalsPlot = GraphicsLayoutWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.SignalsPlot.sizePolicy().hasHeightForWidth())
        self.SignalsPlot.setSizePolicy(sizePolicy)
        self.SignalsPlot.setObjectName("SignalsPlot")
        self.verticalLayout_4.addWidget(self.SignalsPlot)
        self.modelOFFPlot = PlotWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.modelOFFPlot.sizePolicy().hasHeightForWidth())
        self.modelOFFPlot.setSizePolicy(sizePolicy)
        self.modelOFFPlot.setObjectName("modelOFFPlot")
        self.verticalLayout_4.addWidget(self.modelOFFPlot)
        self.modelONPlot = PlotWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.modelONPlot.sizePolicy().hasHeightForWidth())
        self.modelONPlot.setSizePolicy(sizePolicy)
        self.modelONPlot.setObjectName("modelONPlot")
        self.verticalLayout_4.addWidget(self.modelONPlot)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectModelOFFBtn.setText(_translate("MainWindow", "Get Model OFF"))
        self.offThreshLabel.setText(_translate("MainWindow", "Thresh OFF [0 - 1]:"))
        self.inputThreshOFF.setText(_translate("MainWindow", "0.5"))
        self.selectModelONBtn.setText(_translate("MainWindow", "Get Model ON"))
        self.onThreshLabel.setText(_translate("MainWindow", "Thresh ON [0 -1]:"))
        self.inputThreshON.setText(_translate("MainWindow", "0.5"))
        self.labelStreams.setText(_translate("MainWindow", "LSL Streams"))
        self.updateStreamsBtn.setText(_translate("MainWindow", "Update Streams"))
        self.StartStreamBtn.setText(_translate("MainWindow", "Start!"))

from pyqtgraph import GraphicsLayoutWidget, PlotWidget
