# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toggle_stim.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(530, 348)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.UpdateStreamsBtn = QtWidgets.QPushButton(self.frame)
        self.UpdateStreamsBtn.setObjectName("UpdateStreamsBtn")
        self.verticalLayout.addWidget(self.UpdateStreamsBtn)
        self.StreamList = QtWidgets.QListWidget(self.frame)
        self.StreamList.setObjectName("StreamList")
        self.verticalLayout.addWidget(self.StreamList)
        self.StartBtn = QtWidgets.QPushButton(self.frame)
        self.StartBtn.setObjectName("StartBtn")
        self.verticalLayout.addWidget(self.StartBtn)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.UpdateCoordsBtn = QtWidgets.QPushButton(self.frame_3)
        self.UpdateCoordsBtn.setObjectName("UpdateCoordsBtn")
        self.horizontalLayout.addWidget(self.UpdateCoordsBtn)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setAutoFillBackground(False)
        self.frame_4.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2.addWidget(self.frame_4)
        self.TurnStimONBtn = QtWidgets.QPushButton(self.frame_2)
        self.TurnStimONBtn.setObjectName("TurnStimONBtn")
        self.verticalLayout_2.addWidget(self.TurnStimONBtn)
        self.TurnStimOFFBtn = QtWidgets.QPushButton(self.frame_2)
        self.TurnStimOFFBtn.setObjectName("TurnStimOFFBtn")
        self.verticalLayout_2.addWidget(self.TurnStimOFFBtn)
        self.horizontalLayout_2.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 530, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "LSL Streams:"))
        self.UpdateStreamsBtn.setText(_translate("MainWindow", "Update Streams"))
        self.StartBtn.setText(_translate("MainWindow", "Start"))
        self.label_2.setText(_translate("MainWindow", "Stim Controller"))
        self.UpdateCoordsBtn.setText(_translate("MainWindow", "Find Button Coords"))
        self.TurnStimONBtn.setText(_translate("MainWindow", "Turn Stim ON"))
        self.TurnStimOFFBtn.setText(_translate("MainWindow", "Turn Stim OFF"))

